#ifndef MY_VOCA_LIST_H
#define MY_VOCA_LIST_H
#include "MyVoca.h"
int NUM_MY_TOEIC_VOCA = 100;
#endif

MyVoca myToeicVocaList[]=
{
MyVoca("mean", NOUN, { "average", "norm", "median", "middle", "midpoint", "(ant) extremity" }, { "the mean error","the golden mean", "the arithmetical mean", "the geometric mean" }),
MyVoca("deteriorate", VERB, { "Decline", "worsen"}, { "Tears welled up when I heard that my grandmother, who was close to me, was deteriorate than yesterday." }),
MyVoca("utility", NOUN, { "Function", "efficiency" }, { "We always believe that utility is more important than the low price of the product." }),
MyVoca("offer", NOUN, { "proposal" }, { "He accepted out offer to write the business plan." }),
MyVoca("initiative", NOUN, { "Advantage","start" }, { "We have no initiative this fight, so we have no choice but to stay in the corner and keep quiet." }),
MyVoca("compromise", NOUN, { "give-and-take", "bargaining", "accommodation" }, { "The couple made a compromise and ordered food to take out." }),
MyVoca("correspond", VERB, { "Communicate", "match" }, { "When I checked the fingerprints left by the suspect , it became clear that he was the culprit because they were corresponded" }),
MyVoca("delegate", NOUN, { "representative", "agent", "substitute" }, { "The conference was attended by delegates from 56 countries." }),
MyVoca("refrain", VERB, { "Avoid", "halt" }, { "I'm looking for another high-paying job because I'm determined to refrain the company." }),
MyVoca("foster", VERB, { "nurture", "raise", "promote", "advance" }, { "We couldn¡¯t adopt a child, so we decided to foster." }),
MyVoca("process", NOUN, { "Advance", "movement" }, { "You have to go through a special process to do this, and that's a tricky step." }),
MyVoca("revise", VERB, { "Edit", "change" }, { "I was shocked to hear that the manuscript had to be revised because of its high plagiarism rate." }),
MyVoca("imperative", NOUN, { "necessity", "essential", "requirement" }, { "In ¡®Go away!¡¯ the verb is in the imperative" }),
MyVoca("compatible",ADJ,{"Harmonius","consistent"},{"The two primitive tribes have long been rivals, but since the incident, they are now fully compatible."}),
MyVoca("construct",ADJ,{"labored","comples"},{"This statue is so elaborate that it is hard to believe it was made by human."}),
MyVoca("entail",VERB,{"invlove","require"},{"This disease, which killed half of the population, entails complications, so special attention is required."}),
MyVoca("endure",VERB,{"last","remain"},{"It takes a strong mind and a strong body to endure the great pain of disease"}),
MyVoca("cordially",ADV,{"Warmly","kindly"},{"He was always talking to me strictly, but I was surprised that he suddenly spoke cordially to me."}),
MyVoca("succint",ADJ,{"Brief","kindly"},{"He was always talking to me strictly, but I was surprised that he suddenly spoke cordially to me."}),
MyVoca("premise",NOUN,{"Ground","thesis"},{"My argument is highly reliable because the thesis written by the professor is a premise"}),
MyVoca("abide",VERB,{"Tolerate","accept"},{"The only reason I'm abiding all the humiliation is because I want to succeed."}),
MyVoca("obligate",VERB,{"Constrain","bind"},{"obligating will cause a lot of resistance and will be the responsibility of the state"}),
MyVoca("resolve",VERB,{"Decide","determine"},{"It is obligate for men over the age of 20 to go to the military in South Korea."}),
MyVoca("compare",VERB,{"Contrast","balance"},{"By comparing your manuscript with mine, I can see that you did a much better job."}),
MyVoca("satisfy",VERB,{"Indulge","please"},{"I'm pretty worried about what kind of gift I should give her to satisfy her birthday."}),
MyVoca("expire",VERB,{"Indulge","please"},{"The passport I used on my last trip has expired, so I have to get it issued again."}),
MyVoca("administer",VERB,{"Manage","dispense"},{"To administer the company my father inherited, I need talented people, but I also need that much money."}),
MyVoca("substitute",VERB,{"Backup","ghost"},{"Let's all think about what substitute we can replace that food and drink in this emergency."}),
MyVoca("adverse",ADJ,{"Harmful","negative"},{"He seemed to speak for himself, but in fact he was only putting a adverse image on himself."}),
MyVoca("register",VERB,{"Record","enrol"},{"He eventually registered himself as a candidate for the election and showed a look of anticipation."}),
MyVoca("specific",ADJ,{"Particular","precise"},{"The animal has a specific pattern, which looks like a butterfly and is inaccessible to predators."}),
MyVoca("mediate",VERB,{"Intervene","intercede"},{"I made a tremendous effort to mediate the fight between the members of the party I joined."}),
MyVoca("accommodate",VERB,{"Take in ","aid"},{"A temporary residential facility was built to accommodate a large number of refugees across the border."}),
MyVoca("frequent",ADJ,{"Recurring","repeated"},{"Amazon is one of the areas where it rains a lot due to the frequent rainy season."}),
MyVoca("revenue",VERB,{"Income","profits"},{"The corona virus has reduced revenue by almost half, making it difficult to make a living."}),
MyVoca("procure",VERB,{"Obtain","acquire"},{"I tried so hard to procure a job, but it failed all the time and time again"}),
MyVoca("diverse",ADJ,{"Various","different"},{"The peacock at the zoo had so many diverse patterns that it was so fascinating."}),
MyVoca("prerequisite",NOUN,{"Needed","necessary"},{"The task is a prerequisite for carrying out other tasks, so it must be resolved unconditionally."}),
MyVoca("accurate",ADJ,{"Precise","close"},{"The detective's reasoning was so accurate that my mother and I sat there in surprise."}),
MyVoca("integral",ADJ,{"Essentail","basic"},{"The dog is loved by our boss because it has become an integral part of life."}),
MyVoca("endorse",VERB,{"Approve","supprt"},{"If anyone else finds out that I endorse the presidential candidate, I'll hear some bad things."}),
MyVoca("rectify",VERB,{"Correct","right"},{"Strict discipline and behavioral regulations are needed to rectify the child's bad habits even now."}),
MyVoca("mandatory",ADJ,{"Compulsory","binding"},{"Men over the age of 20 should not protest because it is mandatory for them to go to the military."}),
MyVoca("consistent",ADJ,{"Steady","in keeping"},{"My favorite valley is the reason why I like it because it feels consistent whenever I go."}),
MyVoca("quality",NOUN,{"Excellency","state"},{"I liked the product because it was so pretty, but I didn't know what the quality was, so I thought about whether to buy it or not."}),
MyVoca("dominate",VERB,{"Control","direct"},{"In the world under his domination, anyone who disobeys him is condemned to death and needs to be careful."}),
MyVoca("retail",NOUN,{"Trade","market"},{"There was a radish that I wanted to eat, but I could buy it all by retail, so I bought it cheaply."}),
MyVoca("invent",VERB,{"Create","make"},{"A few centuries ago, Edison invented the light bulb, and thanks to it, we were able to avoid darkening at night."}),
MyVoca("invoice",NOUN,{"Bill","charge"},{"There is no way to receive an invoice for the item, although you need to have an invoice for it to get a cash receipt."}),
MyVoca("verify",VERB,{"Confirm","check"},{"I want to verify the truth of the case with my own eyes, so let's go to the place where it happened."}),
MyVoca("deduct",VERB,{"Subtract","remove"},{"It's not that easy to take on all kinds of obligations to get a tax deduction."}),
MyVoca("accure",VERB,{"Accumulate","collect"},{"A rich man in the Middle East published a book that wrote things to do to accure wealth."}),
MyVoca("decline",NOUN,{"Flop","dive"},{"The decline in the company's stock prices has left all those who invested in stocks devastated."}),
MyVoca("liquidate",VERB,{"Convert","cash"},{"I've done everything I can to liquidate the debt I've been living for nearly 40 years, but I'm still not good enough."}),
MyVoca("aggresive",ADJ,{"Hostile","offensive"},{"The lion I saw at the zoo was so aggressive that it was hard to get close."}),
MyVoca("plmmet",VERB,{"Plunge","drop"},{"As the operating profit of the company, which used to be popular in our country, plummeted, the executives of the company urgently convened."}),
MyVoca("waive",VERB,{"Disregard","give up"},{"I wanted to be a basketball player, but I waived my dream of becoming a basketball player due to a serious injury I suffered a while ago."}),
MyVoca("subsidiary",ADJ,{"Secondary","lesser"},{"If you don't select an subsidiary option for the product, it will be very difficult to use the product."}),
MyVoca("bilateral",ADJ,{"Mutual","two-sided"},{"The analysis of the traffic accident found that both the victim and the suspect were at bilateral fault."}),
MyVoca("audit",NOUN,{"Review","survey"},{"An audit was conducted at our company, and everyone stopped all work and prepared for the audit."}),
MyVoca("budget",NOUN,{"Allowance","quota"},{"The budget for this summer trip is much more expensive than the money we saved."}),
MyVoca("reconcile",VERB,{"Resolve","reunite"},{"I tried hard to reconcile them because two of my best friends fought, but they ended up in vain."}),
MyVoca("commit",VERB,{"Do","perform"},{"He thoroughly hid the scene after committing the murder, but the police eventually found traces of the criminal."}),
MyVoca("withdraw",VERB,{"Take out","extract"},{"The protesters, who had been opposed to the government's politics, eventually withdrawed after being crushed by the police's strong crackdown."}),
MyVoca("yield",VERB,{"Bow","give in"},{"Although they worked hard in snow removal, they yielded, not to be overwhelmed by the amount of snow pouring down"}),
MyVoca("affiliate",VERB,{"Join","incorporate"},{"I planned the assassination to affiliate with him, but the police found out that my plan "}),
MyVoca("intervention",NOUN,{"Involvement","Intercession"},{"To transfer shares of our company, we have started price intervention with the person who wants to transfer shares."}),
MyVoca("scrutiny",NOUN,{"Study","examination"},{"The prosecution began a scrutiny on the premise that his crime is suspected to be innocent."}),
MyVoca("consolidate",VERB,{"Strengthen","secure"},{"The organization, called the best in the country, began to gather to consolidate rival organizations."}),
MyVoca("perceptive",ADJ,{"Insightful","reponsive"},{"I think if we just pick the perceptive people and put them in that job, we'll be able to finish."}),
MyVoca("weave",VERB,{"Knit","braid"},{"I weaved the muffler for my boyfriend all week, but I still haven't finished it."}),
MyVoca("fluctuate",VERB,{"Change","swing"},{"The stock of the company I invested in fluctuated over a month, and it eventually plunged."}),
MyVoca("legitimate",ADJ,{"Legal","lawful"},{"If you're really determined to live properly, and if this money isn't legitimate earned, then give it back to society right away."}),
MyVoca("collaborate",VERB,{"Team up","cooperate"},{"He and I like to collaborate together, but the results of the cooperation are not so good that we are wondering if we should continue to work together."}),
MyVoca("disrupt",VERB,{"Interrupt","disturb"},{"While I was taking the test, my little brother kept disrupting me, so I scolded my little brother after the exam was over."}),
MyVoca("consent",NOUN,{"Permition","assent"},{"He ran to me crossing the crosswalk and bumped into me, so we had to reach an consent."}),
MyVoca("conform",VERB,{"Fin in","follow"},{"We began to collect things that weighed just right to conform the teacher's brilliant idea of stopping the flood."}),
MyVoca("commodity",NOUN,{"Item","material"},{"As for those commodity, it's a luxury leather fabric from Italy, but it's being sold at a very low price due to inventory processing."}),
MyVoca("apprehensive",ADJ,{"Anxious","alarmed"},{"The dog that I brought to the market recently bit people well, so I was too apprehensive to keep it next to my friend."}),
MyVoca("Tenant",NOUN,{"Resident","renter"},{"The tenant of the apartment house we rent seemed a bit strange, but I tried to ignore it."}),
MyVoca("compromise",NOUN,{"Agreement","understanding"},{"This is a compromise that my brothers and I have come to compromise on the division of our parents' property."}),
MyVoca("secure",ADJ,{"Tight","stable"},{"Her face seemed secure when she managed to escape from a high-rise building that had collapsed hours ago."}),
MyVoca("complete",ADJ,{"Total","perfect"},{"It was said by the designer that it was complete at the time of the design assignment, but it eventually collapsed."}),
MyVoca("common",ADJ,{"Usual","regular"},{"The puppy that resembles the hamster that I used to raise was so common that I could see any park I went to."}),
MyVoca("relinquish",VERB,{"Give up","surrender"},{"He had a turf war with me, but eventually relinquish his field because he was exhausted"}),
MyVoca("coordinate",VERB,{"Harmonize","cooperate"},{"I stayed up all night trying to coordinate all the data about the surgery, but I couldn't finish it."}),
MyVoca("presume",VERB,{"Believe","think"},{"I presume the killer who hit a man at the intersection in the middle of the night is close by."}),
MyVoca("subjective",ADJ,{"Personal","biased"},{"He has a job of observing people, but I think it doesn't fit his subjective character."}),
MyVoca("temporary",ADJ,{"Impermanent","brief"},{"The larvae of cicadas have been in the ground for years, but when they come out in adult form, they have a very temporary life span."}),
MyVoca("excite",VERB,{"Thrill","stir"},{"The roller coaster excites me and makes me feel like my endorphins are coming out of my mouth."}),
MyVoca("predict",VERB,{"Foretell","forecast"},{"Having jobs predicting mountain movements, they warned residents living in villages close to the mountain that landslides were imminent."}),
MyVoca("assort",VERB,{"Group","classify"},{"The teacher assort a group of our own partners and taught us a class about cooperation."}),
MyVoca("incorporate",VERB,{"Include","integrate"},{"The company made various efforts to incorporate chemical-related external companies into its own companies."}),
MyVoca("exquisite",ADJ,{"Elaborate","elegant"},{"The pottery made by famous masters around the world was so exquisite that I couldn't believe my eyes."}),
MyVoca("regulate",VERB,{"Control","manage"},{"As the virus spread around the world, the government issued a related policy to regulate merchants' soaring food prices."}),
MyVoca("board",NOUN,{"Plank","panel"},{"He doesn't know how to ski, but he likes to skateboard, so he goes to the ski resort every year."}),
MyVoca("prohibit",VERB,{"Prevent","forbid"},{"My mom prohibited me and my brother from doing anything bad to my neighbor's dog like last time."}),
MyVoca("expanse",NOUN,{"Area","plain"},{"Whenever I feel down, I want to go to the expanse as wide as the grassland of Mongolia."}),
MyVoca("comprehend",VERB,{"Understand","comprise"},{"She was excellent at comprehending us because she had a job as a psychological counselor."}),
MyVoca("punctual", ADJ, { "On time","prompt" }, { "We had a lot of trust in him because he is always punctual when he promises to anyone." }),
MyVoca("accomodate", VERB, { "Lodge","take in" }, { "The UNICEF donated money internationally to build a cabin for homeless children and accommodate them." }),
MyVoca("incidental", ADJ, { "Contingent","casual" }, { "I bought a nice kettle advertised on home shopping, but I liked the kitchen knife that was provided incidental" }),
};

